apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller-metrics-reader
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 4 }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
