---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries/finalizers
  verbs:
  - update
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sbombastic.sbombastic.rancher.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sbombastic.sbombastic.rancher.io
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - sbombastic.sbombastic.rancher.io
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.sbombastic.rancher.io.sbombastic.rancher.io
  resources:
  - sboms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.sbombastic.rancher.io.sbombastic.rancher.io
  resources:
  - sboms/finalizers
  verbs:
  - update
- apiGroups:
  - storage.sbombastic.rancher.io.sbombastic.rancher.io
  resources:
  - sboms/status
  verbs:
  - get
  - patch
  - update
