apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 4 }}
spec:
  ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
  selector:
    {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 4 }}
  type: ClusterIP 
