apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 4 }}
