apiVersion: v1
kind: Service
metadata:
  name: controller-nats
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
  selector:
    control-plane: "controller-manager"
  type: ClusterIP 
