apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 6 }}
  serviceName: {{ include "sbombastic.fullname" . }}-controller
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 8 }}
    spec:
      containers:
        - command:
            - /controller
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          name: controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: {{ include "sbombastic.fullname" . }}-controller
      terminationGracePeriodSeconds: 10

