version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      kubernetes:
        patterns:
          - "k8s.io/apimachinery"
          - "k8s.io/client-go"
          - "k8s.io/apiserver"
          - "k8s.io/code-generator"
          - "k8s.io/component-base"
          - "sigs.k8s.io/controller-runtime"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
