version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  groups:
    kubernetes:
      patterns:
        - "sigs.k8s.io/controller-runtime"
        - "k8s.io/apimachinery"
        - "k8s.io/client-go"
        - "k8s.io/component-base"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
