apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage-auth-delegator
  namespace: kube-system
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "storage")) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "sbombastic.fullname" . }}-storage
    namespace: {{ .Release.Namespace }}
