apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage-auth-reader
  namespace: kube-system
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "storage")) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "sbombastic.fullname" . }}-storage
    namespace: {{ .Release.Namespace }}
