apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "storage")) | nindent 4 }}
spec:
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" (merge . (dict "Component" "controller")) | nindent 7 }}
    spec:
      serviceAccountName: {{ include "sbombastic.fullname" . }}-storage
      containers:
        - name: storage
          image: {{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag }}
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
