kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" (merge . (dict "Component" "storage")) | nindent 4 }}
