apiVersion: v1
kind: Pod
metadata:
  name: dev-registry
  namespace: default
  labels:
    app: dev-registry
spec:
  containers:
    - name: registry
      image: registry:2.8.3
      ports:
        - containerPort: 5000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: dev-registry
  namespace: default
spec:
  selector:
    app: dev-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http
