apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
  labels:
    worker: "true"
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      worker: "true"
  template:
    metadata:
      labels:
        worker: "true"
    spec:
      serviceAccountName: worker
      containers:
        - name: worker
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/run/worker
              name: run-volume
      volumes:
        - name: run-volume
          emptyDir: {}
