kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "sbombastic.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbombastic.labels" (merge . (dict "Component" "worker")) | nindent 4 }}
