apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      {{ include "sbombastic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" . | nindent 8 }}
        app.kubernetes.io/component: storage
    spec:
      serviceAccountName: {{ include "sbombastic.fullname" . }}-storage
      containers:
        - name: storage
          image: '{{ template "system_default_registry" . }}{{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag }}'
          securityContext:
            {{ include "sbombastic.securityContext" . | nindent 12 }}
          args:
            - --cert-dir=/certs
          {{- if .Values.storage.logLevel }}
            - -log-level={{ .Values.storage.logLevel }}
          {{- end }}
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
          {{- if and .Values.storage .Values.storage.resources }}
          resources:
{{ toYaml .Values.storage.resources | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: cert-volume
              mountPath: /certs
            - name: pg-secret
              mountPath: /pg
              readOnly: true
      volumes:
        - name: cert-volume
          emptyDir: {}
        - name: pg-secret
          secret:
            secretName: {{ include "sbombastic.fullname" . }}-cnpg-cluster-app
