name: Attestion generation
on:
  workflow_call:
    inputs:
      component:
        type: string
        description: "SBOMbastic component"
        required: true
      arch:
        type: string
        description: "Architecture"
        required: true
jobs:
  attest:
    name: Sign attestations and upload as artifacts
    permissions:
      packages: write # Uploading signed artifacts to ghcr.io
      id-token: write # Signing images with cosign
    runs-on: ubuntu-latest
    env:
      CRANE_VERSION: v0.20.5
      CRANE_CHECKSUM: ad4cd9af2568c62c97e346de6d1295ee8c6ce3341f7b71cf02d41292b4532680

    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
      - name: Install the crane command
        run: |
          set -e
          INSTALL_DIR=$HOME/.crane
          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/google/go-containerregistry/releases/download/${{ env.CRANE_VERSION }}/go-containerregistry_Linux_x86_64.tar.gz -o $INSTALL_DIR/crane.tar.gz
          echo "${{ env.CRANE_CHECKSUM }} $INSTALL_DIR/crane.tar.gz" | sha256sum -c
          tar xvf $INSTALL_DIR/crane.tar.gz -C $INSTALL_DIR
          rm $INSTALL_DIR/crane.tar.gz
          echo $INSTALL_DIR >> $GITHUB_PATH
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all digests
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-${{ inputs.component }}-*
          merge-multiple: true
      - name: Retrieve digest
        working-directory: ${{ runner.temp }}/digests
        run: |
          set -e
          DIGEST=$(cat ${{ inputs.component }}-${{ inputs.arch }}.txt)
          echo "DIGEST=${DIGEST}" >> "$GITHUB_ENV"
      - name: Find attestation digest
        run: |
          set -e
          DIGEST=$(crane manifest ghcr.io/${{ github.repository_owner }}/sbombastic/${{ inputs.component }}@${{ env.DIGEST }} \
          | jq -r '.manifests[]
            | select(.annotations["vnd.docker.reference.type"] == "attestation-manifest")
            | .digest')
          echo "ATTESTATION_MANIFEST_DIGEST=${DIGEST}" >> "$GITHUB_ENV"
      - name: Find provenance manifest digest
        run: |
          set -e
          DIGEST=$(crane manifest ghcr.io/${{ github.repository_owner }}/sbombastic/${{ inputs.component }}@${{ env.ATTESTATION_MANIFEST_DIGEST }} |
                      jq -r '.layers[]
                        | select(.annotations["in-toto.io/predicate-type"] == "https://slsa.dev/provenance/v0.2")
                        | .digest')
          echo "PROVENANCE_DIGEST=${DIGEST}" >> "$GITHUB_ENV"
      - name: Sign provenance manifest
        run: |
          cosign sign --yes \
          ghcr.io/${{github.repository_owner}}/sbombastic/${{ inputs.component }}@${{ env.PROVENANCE_DIGEST}}
          cosign verify \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity="https://github.com/${{github.repository_owner}}/sbombastic/.github/workflows/attestation.yml@${{ github.ref }}" \
            ghcr.io/${{github.repository_owner}}/sbombastic/${{ inputs.component }}@${{ env.PROVENANCE_DIGEST}}
      - name: Find SBOM manifest layer digest
        run: |
          set -e
          DIGEST=$(crane manifest ghcr.io/${{github.repository_owner}}/sbombastic/${{ inputs.component }}@${{ env.ATTESTATION_MANIFEST_DIGEST}} |  \
            jq '.layers | map(select(.annotations["in-toto.io/predicate-type"] == "https://spdx.dev/Document")) | map(.digest) | join(" ")')
          echo "SBOM_DIGEST=${DIGEST}" >> "$GITHUB_ENV"
      - name: Download provenance and SBOM files
        run: |
          set -e
          crane blob ghcr.io/${{github.repository_owner}}/sbombastic/${{ inputs.component }}@${{ env.PROVENANCE_DIGEST}} \
            > SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-provenance.json
          sha256sum SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-provenance.json \
            >> SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum.txt
          crane blob ghcr.io/${{github.repository_owner}}/sbombastic/${{ inputs.component }}@${{ env.SBOM_DIGEST}} \
            > SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-sbom.json
          sha256sum SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-sbom.json \
            >> SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum.txt
      - name: Sign checksum file
        run: |
          cosign sign-blob --yes \
            --bundle SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum-cosign.bundle \
            SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum.txt
          cosign verify-blob \
            --bundle SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum-cosign.bundle \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity="https://github.com/${{github.repository_owner}}/sbombastic/.github/workflows/attestation.yml@${{ github.ref }}" \
            SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}-checksum.txt
      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: attestation-SBOMbastic-${{ inputs.component }}-${{ inputs.arch }}
          path: SBOMbastic-${{ inputs.component }}-attestation-${{ inputs.arch }}*