name: Build, Sign, and Generate SBOM, Attestation & Provenance

on:
  workflow_call:
    inputs:
      version:
        type: string

  push:
    branches:
      - "main"
jobs:
  build:
    strategy:
      matrix:
        component: [controller, worker, storage]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
    permissions:
      packages: write # Pushing images to ghcr.io
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}
      - name: Build and push ${{ matrix.component }} for ${{ matrix.arch }}
        id: build-image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile.${{ matrix.component }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          push: true
          sbom: true
          provenance: mode=max
          tags: ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}
          outputs: |
            type=image,push=true,push-by-digest=true,name-canonical=true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build-image.outputs.digest }}"
          echo "${digest}" > "${{ runner.temp }}/digests/${{ matrix.component }}-${{ matrix.arch }}.txt"

      - name: Upload digest
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: digest-${{ matrix.component }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*.txt
          retention-days: 1
  merge:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write # Pushing multi-arch manifest to ghcr.io
    strategy:
      matrix:
        component: [controller, worker, storage]
    steps:
      - name: Download all digests
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-${{ matrix.component }}-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Retrieve tag name (main)
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: |
          echo TAG_NAME=latest >> $GITHUB_ENV

      - name: Retrieve tag name (release)
        if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
        run: |
          echo TAG_NAME=${{ inputs.version }} >> $GITHUB_ENV

      - name: Create and push multi-arch manifest for ${{ matrix.component }}
        id: create-manifest
        working-directory: ${{ runner.temp }}/digests
        run: |
          amd64_digest=$(cat ${{ matrix.component }}-amd64.txt)
          arm64_digest=$(cat ${{ matrix.component }}-arm64.txt)

          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}:${{ env.TAG_NAME }} \
            ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}@${amd64_digest} \
            ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}@${arm64_digest}

          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/sbombastic/${{ matrix.component }}:${{ env.TAG_NAME }}

  attest:
    needs: [merge]
    if: ${{ inputs.version }}
    uses: ./.github/workflows/attestation.yml
    permissions:
      id-token: write # Generating OIDC token for Sigstore/Cosign authentication
      packages: write # Pushing attestations to ghcr.io
    strategy:
      matrix:
        component: [controller, worker, storage]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
    with:
      component: ${{ matrix.component }}
      arch: ${{ matrix.arch }}