name: Update helm charts
on:
  workflow_call:
  workflow_dispatch:
jobs:
  update-sbomscanner-charts:
    name: Update SBOMscanner charts
    runs-on: ubuntu-latest
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@719e3592d124cbf826da704cbe557e1221dd4bba # v2.94.0

      - name: Update SBOMscanner charts
        env:
          # Until this repository is under the kubewarden GitHub organisation
          # It's easier to use the default GITHUB_TOKEN but ultimately
          # it's gonna be better to use a GitHub App token
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli compose apply --file updatecli/updatecli-compose.release.yaml"
